package com.misync.recorder.crypto

import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Wraps and unwraps per-recording data keys (DEKs).
 *
 * Every recording gets its own random AES-256 DEK. The DEK is encrypted ("wrapped") by a
 * key-encryption key that never leaves the Android Keystore, and the wrapped form is stored
 * in the recording's header. Deleting the file therefore destroys the only copy of its key.
 */
interface KeyWrapper {
    fun wrap(dataKey: ByteArray): ByteArray
    fun unwrap(wrapped: ByteArray): ByteArray
}

/**
 * AES-256-GCM key wrapper. [keySupplier] returns the key-encryption key; on device this is an
 * Android Keystore key (see [KeystoreKeyProvider]), in unit tests a plain software key.
 *
 * Wrapped layout: `iv(12) || ciphertext || tag(16)`. The IV is generated by the cipher itself,
 * which is required for Keystore keys created with randomized encryption.
 */
class AesGcmKeyWrapper(private val keySupplier: () -> SecretKey) : KeyWrapper {

    override fun wrap(dataKey: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, keySupplier())
        cipher.updateAAD(AAD)
        val iv = cipher.iv
        require(iv.size == IV_BYTES) { "Unexpected IV length ${iv.size}" }
        return iv + cipher.doFinal(dataKey)
    }

    override fun unwrap(wrapped: ByteArray): ByteArray {
        if (wrapped.size < IV_BYTES + TAG_BYTES) throw CorruptRecordingException("Wrapped key too short")
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            keySupplier(),
            GCMParameterSpec(TAG_BYTES * 8, wrapped, 0, IV_BYTES),
        )
        cipher.updateAAD(AAD)
        return try {
            cipher.doFinal(wrapped, IV_BYTES, wrapped.size - IV_BYTES)
        } catch (e: javax.crypto.AEADBadTagException) {
            throw CorruptRecordingException("Recording key cannot be unwrapped (wrong device key or tampered header)", e)
        }
    }

    companion object {
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val IV_BYTES = 12
        const val TAG_BYTES = 16
        private val AAD = "MISync-DEK-v1".toByteArray()
    }
}

object DataKeys {
    const val KEY_BYTES = 32

    fun generate(random: SecureRandom = SecureRandom()): ByteArray {
        val generator = KeyGenerator.getInstance("AES")
        generator.init(KEY_BYTES * 8, random)
        return generator.generateKey().encoded
    }

    fun toSecretKey(bytes: ByteArray): SecretKey {
        require(bytes.size == KEY_BYTES) { "Data key must be 256 bits" }
        return SecretKeySpec(bytes, "AES")
    }
}

class CorruptRecordingException(message: String, cause: Throwable? = null) : java.io.IOException(message, cause)
